### ISSUE TITLE
Suggestion: add iptables command to the template

### ISSUE THREAD

**Issue by alfetopito** [osiell/ansible-iptables#1]
Hey there,

I just have one suggestion. Rather than add `iptables` to every line, wouldn't be better to just put it inside of the template? Like:

```
# rules.j2
# ...
{% for line in rule.lines %}
iptables {{ line }}
{% endfor %}
```

Or in case you have a reason to have a custom command, I'd say create a variable on defaults/main.yml for the command and standard options if any.

I could create a pull request if you want.

And thanks for this role, saved me a bunch of time.

Cheers!

**Comment by sebalix** [comment]
Hi,

In fact, I like to be able to set any shell commands I want for any purpose (execute a shell script or whatever), even if the `iptables` was the main task. So I set it like this, but maybe this is the name of the role which is not well chosen?
`ansible-interface-event` would have been more appropriate probably.

**Comment by alfetopito** [comment]
Ah, I got it. Closing the ticket then.
